### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by zengxingchen** [tgxs002/HPSv2#12]
Traceback (most recent call last):
  File "d:\human-preference-CLIP\main.py", line 2, in <module>
    import hpsv2
  File "D:\human-preference-CLIP\venv\lib\site-packages\hpsv2\__init__.py", line 7, in <module>
    from . import evaluate as eval
  File "D:\human-preference-CLIP\venv\lib\site-packages\hpsv2\evaluate.py", line 16, in <module>
    from hpsv2.src.training.train import calc_ImageReward, inversion_score
  File "D:\human-preference-CLIP\venv\lib\site-packages\hpsv2\src\training\train.py", line 18, in <module>
    from .data import ImageRewardDataset, RankingDataset
  File "D:\human-preference-CLIP\venv\lib\site-packages\hpsv2\src\training\data.py", line 4, in <module>
    from curses import meta
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by tgxs002** [comment]
You may need a higher version of python, 3.8.10 works on my side.

**Comment by zengxingchen** [comment]
> You may need a higher version of python, 3.8.10 works on my side.

thanks for your kind reply. Its' maybe a problem about windows system. I solve it by `pip install windows-curses`
